### ISSUE TITLE
Update to 2020v10 image

### ISSUE THREAD

**Issue by auscompgeek** [first-rust-competition/cross-images#1]
https://www.ni.com/en-au/support/downloads/drivers/download.frc-game-tools.html

**Comment by emmaworley** [comment]
I've found the system image in the offline installer, but I'd rather avoid downloading everything a network capture from the online installer would be useful.

edit: found a feed at https://download.ni.com/support/nipkg/products/ni-f/ni-frc-2020-game-tools/19.0/released/Packages

**Comment by auscompgeek** [comment]
This looks... awfully similar to a certain distro's package format.

**Comment by auscompgeek** [comment]
Any particular reason why you're using both bsdtar and cabextract?

**Comment by emmaworley** [comment]
I tried throwing opkg at it but it wasn't happy. I think there are some NI Package Manager extensions going on / dependencies in other feeds I haven't been able to find. Ubuntu's bsdtar doesn't seem to handle cab files.

This script is getting pretty nasty.. it would be nice to get opkg to work.

**Comment by emmaworley** [comment]
Looks like it works https://registry.hub.docker.com/r/firstrustcompetition/cross/tags 🎉 
I'll make another issue for cleaning up the script.
